version: "3.7"

services:
  app:
    image: $CI_REGISTRY_IMAGE_DEVOPS/staging:$IMAGE_TAG
    command: >
      sh -c "python manage.py migrate --noinput &&
            gunicorn core.asgi:application --bind 0.0.0.0:8000 --workers 4 --worker-class uvicorn.workers.UvicornWorker"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      # HTTP route
      - traefik.http.routers.${STAGING_STACK_NAME}_app-http.entrypoints=http
      - "traefik.http.routers.${STAGING_STACK_NAME}_app-http.rule=Host(`${STAGING_URL_BACK}`)"
      - traefik.http.middlewares.${STAGING_STACK_NAME}_app-headers.headers.referrerPolicy=no-referrer
      - traefik.http.middlewares.${STAGING_STACK_NAME}_app-headers.headers.stsSeconds=31536000
      - traefik.http.middlewares.${STAGING_STACK_NAME}_app-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.${STAGING_STACK_NAME}_app-headers.headers.stsPreload=true
      # HTTPS route
      - traefik.http.routers.${STAGING_STACK_NAME}_app.entrypoints=https
      - "traefik.http.routers.${STAGING_STACK_NAME}_app.rule=Host(`${STAGING_URL_BACK}`)"
      - traefik.http.routers.${STAGING_STACK_NAME}_app.tls=true
      # Service
      - traefik.http.services.${STAGING_STACK_NAME}_app.loadbalancer.server.port=8000
      # Classic Docker labels
      - track=stable
      - app.gitlab.com/env=staging
    volumes:
      - static_files:/app/staticfiles
      - static:/app/static
    networks:
      - traefik-net

volumes:
  static_files:
  static:

networks:
  default:
  traefik-net:
    external: true
