# Generated by Django 5.2.13 on 2026-05-04 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20, verbose_name='Statut')),
                ('history_filename', models.CharField(max_length=255, verbose_name='Nom du CSV historique')),
                ('future_filename', models.CharField(max_length=255, verbose_name='Nom du CSV futur')),
                ('history_file', models.BinaryField(verbose_name='Contenu CSV historique')),
                ('future_file', models.BinaryField(verbose_name='Contenu CSV futur')),
                ('stock_tampon', models.PositiveIntegerField(default=250, verbose_name='Stock tampon / jour')),
                ('tuning_cfg', models.JSONField(default=dict, verbose_name='Config de tuning retenue')),
                ('tuning_metrics', models.JSONField(default=dict, verbose_name='Métriques de tuning')),
                ('predict_start', models.DateField(blank=True, null=True, verbose_name='Début de prédiction')),
                ('predict_end', models.DateField(blank=True, null=True, verbose_name='Fin de prédiction')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="Message d'erreur")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Prévision',
                'verbose_name_plural': 'Prévisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('school', models.CharField(max_length=255, verbose_name='École')),
                ('reservation_theorique', models.PositiveIntegerField(verbose_name='Réservation théorique')),
                ('delta_learned', models.IntegerField(verbose_name='Delta appris')),
                ('amount_predicted', models.PositiveIntegerField(verbose_name='Quantité prédite (modèle)')),
                ('supplement_humain', models.IntegerField(default=0, verbose_name='Supplément humain')),
                ('final_amount', models.PositiveIntegerField(verbose_name='Quantité finale à préparer')),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app_forecasting.forecast', verbose_name='Prévision parente')),
            ],
            options={
                'verbose_name': 'Ligne de prévision',
                'verbose_name_plural': 'Lignes de prévision',
                'ordering': ['date', 'school'],
            },
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['user', '-created_at'], name='app_forecas_user_id_769bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['status'], name='app_forecas_status_ede8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastrow',
            index=models.Index(fields=['forecast', 'date'], name='app_forecas_forecas_094426_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastrow',
            index=models.Index(fields=['forecast', 'school'], name='app_forecas_forecas_270953_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastrow',
            constraint=models.UniqueConstraint(fields=('forecast', 'date', 'school'), name='unique_forecast_date_school'),
        ),
    ]
