# Generated by Django 5.2.13 on 2026-05-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_forecasting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='forecastrow',
            name='unique_forecast_date_school',
        ),
    ]
