# Generated by Django 5.2.13 on 2026-05-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forecasting', '0002_remove_forecastrow_unique_forecast_date_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre'),
        ),
    ]
